apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "dfstender.fullname" . }}-secret
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "dfstender.fullname" . }}-secret
      type: Opaque
      labels:
        environment: ""
      data:
        - objectName: dbusernamealias
          key: DB_USERNAME
        - objectName: dbpasswordalias
          key: DB_PASSWORD
  parameters:
    keyvaultName: "dfs-tender-k8s-key-vault"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "755ed1d8-ba64-4cf9-89ef-87230e0dcde8" # The clientId of the addon-created managed identity
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: "dfstender-db-username"
          objectType: secret              # Object types: secret, key or cert
          objectAlias: dbusernamealias
          objectVersion: ""
        - |
          objectName: "dfstender-db-password"       # In this example, 'ExampleSecret'
          objectType: secret              # Object types: secret, key or cert
          objectAlias: dbpasswordalias
          objectVersion: ""
    tenantId: "0f077ed7-64f1-4ccf-a8ab-4a231535f254"            # the tenant ID containing the Azure Key Vault instance
