apiVersion: v1
kind: Service
metadata:
  name: {{ include "dfstender.fullname" . }}
  labels:
    {{- include "dfstender.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8085
      name: http
  selector:
    {{- include "dfstender.selectorLabels" . | nindent 4 }}