apiVersion: v1
kind: Service
metadata:
  name: dfstender-ui
  labels:
    app.kubernetes.io/instance: dfstender
    app.kubernetes.io/name: dfstender
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 8084
      name: http
  selector: dfstender-ui
