apiVersion: v1
kind: Service
metadata:
  name: dfstender-ui
  labels:
    app.kubernetes.io/instance: dfstender-ui
    app.kubernetes.io/name: dfstender-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: http
  selector:
    app.kubernetes.io/instance: dfstender-ui
